// <auto-generated />
namespace Pairme.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ImageLink : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageLink));
        
        string IMigrationMetadata.Id
        {
            get { return "201504140124426_ImageLink"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
