//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pairme
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string Discriminator { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public Nullable<int> Age { get; set; }
        public string ImageLink { get; set; }
        public string Summary { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> MatchGenderID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> LookingForID { get; set; }
        public Nullable<int> RelationshipStatusID { get; set; }
        public Nullable<int> EthnicityID { get; set; }
        public Nullable<int> BodyTypeID { get; set; }
        public Nullable<int> ProfessionID { get; set; }
        public Nullable<int> EducationID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> ChildrenID { get; set; }
        public Nullable<int> SmokesID { get; set; }
        public Nullable<int> DrinksID { get; set; }
        public Nullable<int> DrugsID { get; set; }
        public string LookingForSummary { get; set; }
        public Nullable<int> Height { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual BodyType BodyType { get; set; }
        public virtual Child Child { get; set; }
        public virtual Country Country { get; set; }
        public virtual Drink Drink { get; set; }
        public virtual Drug Drug { get; set; }
        public virtual Education Education { get; set; }
        public virtual Ethnicity Ethnicity { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual LookingFor LookingFor { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual RelationshipStatu RelationshipStatu { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual Smoke Smoke { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
