//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pairme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender
    {
        public Gender()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.AspNetUsers1 = new HashSet<AspNetUser>();
        }
    
        public int ID { get; set; }
        public string GenderName { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers1 { get; set; }
    }
}
